/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EvaluatorInterface extends utils.Interface {
  functions: {
    "assignedRank(address)": FunctionFragment;
    "bytes32ToString(bytes32)": FunctionFragment;
    "ex1_testERC721()": FunctionFragment;
    "ex2a_getAnimalToCreateAttributes()": FunctionFragment;
    "ex2b_testDeclaredAnimal(uint256)": FunctionFragment;
    "ex3_testRegisterBreeder()": FunctionFragment;
    "ex4_testDeclareAnimal()": FunctionFragment;
    "ex5_declareDeadAnimal()": FunctionFragment;
    "ex6a_auctionAnimal_offer()": FunctionFragment;
    "ex6b_auctionAnimal_buy(uint256)": FunctionFragment;
    "exerciceProgression(address,uint256)": FunctionFragment;
    "hasBeenPaired(address)": FunctionFragment;
    "nextValueStoreRank()": FunctionFragment;
    "readLegs(address)": FunctionFragment;
    "readName(address)": FunctionFragment;
    "readSex(address)": FunctionFragment;
    "readWings(address)": FunctionFragment;
    "setRandomValuesStore(string[20],uint256[20],uint256[20],bool[20])": FunctionFragment;
    "studentExerciceSolution(address)": FunctionFragment;
    "submitExercice(address)": FunctionFragment;
    "teachers(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "assignedRank"
      | "bytes32ToString"
      | "ex1_testERC721"
      | "ex2a_getAnimalToCreateAttributes"
      | "ex2b_testDeclaredAnimal"
      | "ex3_testRegisterBreeder"
      | "ex4_testDeclareAnimal"
      | "ex5_declareDeadAnimal"
      | "ex6a_auctionAnimal_offer"
      | "ex6b_auctionAnimal_buy"
      | "exerciceProgression"
      | "hasBeenPaired"
      | "nextValueStoreRank"
      | "readLegs"
      | "readName"
      | "readSex"
      | "readWings"
      | "setRandomValuesStore"
      | "studentExerciceSolution"
      | "submitExercice"
      | "teachers"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "assignedRank",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bytes32ToString",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "ex1_testERC721",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ex2a_getAnimalToCreateAttributes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ex2b_testDeclaredAnimal",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ex3_testRegisterBreeder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ex4_testDeclareAnimal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ex5_declareDeadAnimal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ex6a_auctionAnimal_offer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ex6b_auctionAnimal_buy",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "exerciceProgression",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBeenPaired",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "nextValueStoreRank",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "readLegs",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "readName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "readSex",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "readWings",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRandomValuesStore",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<boolean>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "studentExerciceSolution",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "submitExercice",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "teachers",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "assignedRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bytes32ToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex1_testERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex2a_getAnimalToCreateAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex2b_testDeclaredAnimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex3_testRegisterBreeder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex4_testDeclareAnimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex5_declareDeadAnimal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex6a_auctionAnimal_offer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ex6b_auctionAnimal_buy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "exerciceProgression",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasBeenPaired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextValueStoreRank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "readLegs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "readName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "readSex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "readWings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRandomValuesStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentExerciceSolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitExercice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "teachers", data: BytesLike): Result;

  events: {
    "constructedCorrectly(address)": EventFragment;
    "newRandomAnimalAttributes(string,uint256,uint256,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "constructedCorrectly"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "newRandomAnimalAttributes"): EventFragment;
}

export interface constructedCorrectlyEventObject {
  erc20Address: string;
}
export type constructedCorrectlyEvent = TypedEvent<
  [string],
  constructedCorrectlyEventObject
>;

export type constructedCorrectlyEventFilter =
  TypedEventFilter<constructedCorrectlyEvent>;

export interface newRandomAnimalAttributesEventObject {
  name: string;
  legs: BigNumber;
  sex: BigNumber;
  wings: boolean;
}
export type newRandomAnimalAttributesEvent = TypedEvent<
  [string, BigNumber, BigNumber, boolean],
  newRandomAnimalAttributesEventObject
>;

export type newRandomAnimalAttributesEventFilter =
  TypedEventFilter<newRandomAnimalAttributesEvent>;

export interface Evaluator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EvaluatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    assignedRank(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    bytes32ToString(
      _bytes32: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    ex1_testERC721(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex2a_getAnimalToCreateAttributes(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex2b_testDeclaredAnimal(
      animalNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex3_testRegisterBreeder(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex4_testDeclareAnimal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex5_declareDeadAnimal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex6a_auctionAnimal_offer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ex6b_auctionAnimal_buy(
      animalForSale: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    exerciceProgression(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hasBeenPaired(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    nextValueStoreRank(overrides?: CallOverrides): Promise<[BigNumber]>;

    readLegs(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    readName(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    readSex(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    readWings(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setRandomValuesStore(
      _randomNames: PromiseOrValue<string>[],
      _randomLegs: PromiseOrValue<BigNumberish>[],
      _randomSex: PromiseOrValue<BigNumberish>[],
      _randomWings: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    studentExerciceSolution(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    submitExercice(
      studentExercice: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    teachers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  assignedRank(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  bytes32ToString(
    _bytes32: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  ex1_testERC721(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex2a_getAnimalToCreateAttributes(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex2b_testDeclaredAnimal(
    animalNumber: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex3_testRegisterBreeder(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex4_testDeclareAnimal(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex5_declareDeadAnimal(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex6a_auctionAnimal_offer(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ex6b_auctionAnimal_buy(
    animalForSale: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  exerciceProgression(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hasBeenPaired(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  nextValueStoreRank(overrides?: CallOverrides): Promise<BigNumber>;

  readLegs(
    studentAddres: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  readName(
    studentAddres: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  readSex(
    studentAddres: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  readWings(
    studentAddres: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setRandomValuesStore(
    _randomNames: PromiseOrValue<string>[],
    _randomLegs: PromiseOrValue<BigNumberish>[],
    _randomSex: PromiseOrValue<BigNumberish>[],
    _randomWings: PromiseOrValue<boolean>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  studentExerciceSolution(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  submitExercice(
    studentExercice: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  teachers(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    assignedRank(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytes32ToString(
      _bytes32: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    ex1_testERC721(overrides?: CallOverrides): Promise<void>;

    ex2a_getAnimalToCreateAttributes(overrides?: CallOverrides): Promise<void>;

    ex2b_testDeclaredAnimal(
      animalNumber: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    ex3_testRegisterBreeder(overrides?: CallOverrides): Promise<void>;

    ex4_testDeclareAnimal(overrides?: CallOverrides): Promise<void>;

    ex5_declareDeadAnimal(overrides?: CallOverrides): Promise<void>;

    ex6a_auctionAnimal_offer(overrides?: CallOverrides): Promise<void>;

    ex6b_auctionAnimal_buy(
      animalForSale: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    exerciceProgression(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hasBeenPaired(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    nextValueStoreRank(overrides?: CallOverrides): Promise<BigNumber>;

    readLegs(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readName(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    readSex(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readWings(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setRandomValuesStore(
      _randomNames: PromiseOrValue<string>[],
      _randomLegs: PromiseOrValue<BigNumberish>[],
      _randomSex: PromiseOrValue<BigNumberish>[],
      _randomWings: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;

    studentExerciceSolution(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    submitExercice(
      studentExercice: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    teachers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "constructedCorrectly(address)"(
      erc20Address?: null
    ): constructedCorrectlyEventFilter;
    constructedCorrectly(erc20Address?: null): constructedCorrectlyEventFilter;

    "newRandomAnimalAttributes(string,uint256,uint256,bool)"(
      name?: null,
      legs?: null,
      sex?: null,
      wings?: null
    ): newRandomAnimalAttributesEventFilter;
    newRandomAnimalAttributes(
      name?: null,
      legs?: null,
      sex?: null,
      wings?: null
    ): newRandomAnimalAttributesEventFilter;
  };

  estimateGas: {
    assignedRank(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    bytes32ToString(
      _bytes32: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ex1_testERC721(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex2a_getAnimalToCreateAttributes(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex2b_testDeclaredAnimal(
      animalNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex3_testRegisterBreeder(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex4_testDeclareAnimal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex5_declareDeadAnimal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex6a_auctionAnimal_offer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ex6b_auctionAnimal_buy(
      animalForSale: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    exerciceProgression(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hasBeenPaired(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    nextValueStoreRank(overrides?: CallOverrides): Promise<BigNumber>;

    readLegs(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readName(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readSex(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    readWings(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setRandomValuesStore(
      _randomNames: PromiseOrValue<string>[],
      _randomLegs: PromiseOrValue<BigNumberish>[],
      _randomSex: PromiseOrValue<BigNumberish>[],
      _randomWings: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    studentExerciceSolution(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    submitExercice(
      studentExercice: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    teachers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    assignedRank(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bytes32ToString(
      _bytes32: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ex1_testERC721(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex2a_getAnimalToCreateAttributes(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex2b_testDeclaredAnimal(
      animalNumber: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex3_testRegisterBreeder(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex4_testDeclareAnimal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex5_declareDeadAnimal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex6a_auctionAnimal_offer(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ex6b_auctionAnimal_buy(
      animalForSale: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    exerciceProgression(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasBeenPaired(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    nextValueStoreRank(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readLegs(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readName(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readSex(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    readWings(
      studentAddres: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setRandomValuesStore(
      _randomNames: PromiseOrValue<string>[],
      _randomLegs: PromiseOrValue<BigNumberish>[],
      _randomSex: PromiseOrValue<BigNumberish>[],
      _randomWings: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    studentExerciceSolution(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    submitExercice(
      studentExercice: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    teachers(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
