/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20TD } from "./ERC20TD";
export type { EvaNFT } from "./EvaNFT";
export type { Evaluator } from "./Evaluator";
export type { Evaluator2 } from "./Evaluator2";
export type { IExerciceSolution } from "./IExerciceSolution";
