/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20TD__factory } from "./ERC20TD__factory";
export { EvaNFT__factory } from "./EvaNFT__factory";
export { Evaluator__factory } from "./Evaluator__factory";
export { Evaluator2__factory } from "./Evaluator2__factory";
export { IExerciceSolution__factory } from "./IExerciceSolution__factory";
